# Example secret file - DO NOT commit actual credentials
# Copy this file to secret.yaml and update with your values:
#   cp secret.example.yaml secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: infrastructure
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: changeme123
  POSTGRES_DB: playground
